jobs:
  test:
    docker:
      - image: insightinfrastructure/icon-ci:v0.2.0
    steps:
      - checkout
      - run: |
          make test
orbs:
  go: circleci/go@0.2.0
  node: circleci/node@1.1.6
version: 2.1
workflows:
  default:
    jobs:
      - test:
          context: aws-ci-1
  version: 2
